// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ApisColumns holds the columns for the "apis" table.
	ApisColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
	}
	// ApisTable holds the schema information for the "apis" table.
	ApisTable = &schema.Table{
		Name:       "apis",
		Columns:    ApisColumns,
		PrimaryKey: []*schema.Column{ApisColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ApisTable,
	}
)

func init() {
}
