// Code generated by goctl. DO NOT EDIT.
// Source: example_rpc.proto

package examplerpc

import (
	"context"

	"github.com/Sanagiig/fox-admin-core/example_rpc/types/example_rpc"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BaseIDInt32Resp  = example_rpc.BaseIDInt32Resp
	BaseIDInt64Resp  = example_rpc.BaseIDInt64Resp
	BaseIDResp       = example_rpc.BaseIDResp
	BaseIDStringResp = example_rpc.BaseIDStringResp
	BaseIDUint32Resp = example_rpc.BaseIDUint32Resp
	BaseResp         = example_rpc.BaseResp
	BaseUUIDResp     = example_rpc.BaseUUIDResp
	Empty            = example_rpc.Empty
	IDInt32Req       = example_rpc.IDInt32Req
	IDInt64Req       = example_rpc.IDInt64Req
	IDReq            = example_rpc.IDReq
	IDStringReq      = example_rpc.IDStringReq
	IDUint32Req      = example_rpc.IDUint32Req
	IDsInt32Req      = example_rpc.IDsInt32Req
	IDsInt64Req      = example_rpc.IDsInt64Req
	IDsReq           = example_rpc.IDsReq
	IDsStringReq     = example_rpc.IDsStringReq
	IDsUint32Req     = example_rpc.IDsUint32Req
	PageInfoReq      = example_rpc.PageInfoReq
	UUIDReq          = example_rpc.UUIDReq
	UUIDsReq         = example_rpc.UUIDsReq

	ExampleRpc interface {
		InitDatabase(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*BaseResp, error)
	}

	defaultExampleRpc struct {
		cli zrpc.Client
	}
)

func NewExampleRpc(cli zrpc.Client) ExampleRpc {
	return &defaultExampleRpc{
		cli: cli,
	}
}

func (m *defaultExampleRpc) InitDatabase(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*BaseResp, error) {
	client := example_rpc.NewExampleRpcClient(m.cli.Conn())
	return client.InitDatabase(ctx, in, opts...)
}
