// Code generated by goctl. DO NOT EDIT.
// Source: example_rpc.proto

package server

import (
	"context"

	"github.com/Sanagiig/fox-admin-core/example_rpc/internal/logic/base"
	"github.com/Sanagiig/fox-admin-core/example_rpc/internal/svc"
	"github.com/Sanagiig/fox-admin-core/example_rpc/types/example_rpc"
)

type ExampleRpcServer struct {
	svcCtx *svc.ServiceContext
	example_rpc.UnimplementedExampleRpcServer
}

func NewExampleRpcServer(svcCtx *svc.ServiceContext) *ExampleRpcServer {
	return &ExampleRpcServer{
		svcCtx: svcCtx,
	}
}

func (s *ExampleRpcServer) InitDatabase(ctx context.Context, in *example_rpc.Empty) (*example_rpc.BaseResp, error) {
	l := base.NewInitDatabaseLogic(ctx, s.svcCtx)
	return l.InitDatabase(in)
}
