// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Sanagiig/fox-admin-core/example_rpc/ent/examplerpc"
	"github.com/Sanagiig/fox-admin-core/example_rpc/ent/predicate"
)

// ExampleRpcUpdate is the builder for updating ExampleRpc entities.
type ExampleRpcUpdate struct {
	config
	hooks    []Hook
	mutation *ExampleRpcMutation
}

// Where appends a list predicates to the ExampleRpcUpdate builder.
func (eru *ExampleRpcUpdate) Where(ps ...predicate.ExampleRpc) *ExampleRpcUpdate {
	eru.mutation.Where(ps...)
	return eru
}

// Mutation returns the ExampleRpcMutation object of the builder.
func (eru *ExampleRpcUpdate) Mutation() *ExampleRpcMutation {
	return eru.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (eru *ExampleRpcUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, eru.sqlSave, eru.mutation, eru.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (eru *ExampleRpcUpdate) SaveX(ctx context.Context) int {
	affected, err := eru.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (eru *ExampleRpcUpdate) Exec(ctx context.Context) error {
	_, err := eru.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (eru *ExampleRpcUpdate) ExecX(ctx context.Context) {
	if err := eru.Exec(ctx); err != nil {
		panic(err)
	}
}

func (eru *ExampleRpcUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(examplerpc.Table, examplerpc.Columns, sqlgraph.NewFieldSpec(examplerpc.FieldID, field.TypeInt))
	if ps := eru.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if n, err = sqlgraph.UpdateNodes(ctx, eru.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{examplerpc.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	eru.mutation.done = true
	return n, nil
}

// ExampleRpcUpdateOne is the builder for updating a single ExampleRpc entity.
type ExampleRpcUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ExampleRpcMutation
}

// Mutation returns the ExampleRpcMutation object of the builder.
func (eruo *ExampleRpcUpdateOne) Mutation() *ExampleRpcMutation {
	return eruo.mutation
}

// Where appends a list predicates to the ExampleRpcUpdate builder.
func (eruo *ExampleRpcUpdateOne) Where(ps ...predicate.ExampleRpc) *ExampleRpcUpdateOne {
	eruo.mutation.Where(ps...)
	return eruo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (eruo *ExampleRpcUpdateOne) Select(field string, fields ...string) *ExampleRpcUpdateOne {
	eruo.fields = append([]string{field}, fields...)
	return eruo
}

// Save executes the query and returns the updated ExampleRpc entity.
func (eruo *ExampleRpcUpdateOne) Save(ctx context.Context) (*ExampleRpc, error) {
	return withHooks(ctx, eruo.sqlSave, eruo.mutation, eruo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (eruo *ExampleRpcUpdateOne) SaveX(ctx context.Context) *ExampleRpc {
	node, err := eruo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (eruo *ExampleRpcUpdateOne) Exec(ctx context.Context) error {
	_, err := eruo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (eruo *ExampleRpcUpdateOne) ExecX(ctx context.Context) {
	if err := eruo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (eruo *ExampleRpcUpdateOne) sqlSave(ctx context.Context) (_node *ExampleRpc, err error) {
	_spec := sqlgraph.NewUpdateSpec(examplerpc.Table, examplerpc.Columns, sqlgraph.NewFieldSpec(examplerpc.FieldID, field.TypeInt))
	id, ok := eruo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ExampleRpc.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := eruo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, examplerpc.FieldID)
		for _, f := range fields {
			if !examplerpc.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != examplerpc.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := eruo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	_node = &ExampleRpc{config: eruo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, eruo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{examplerpc.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	eruo.mutation.done = true
	return _node, nil
}
