// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Sanagiig/fox-admin-core/example_rpc/ent/examplerpc"
)

// ExampleRpc is the model entity for the ExampleRpc schema.
type ExampleRpc struct {
	config
	// ID of the ent.
	ID           int `json:"id,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ExampleRpc) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case examplerpc.FieldID:
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ExampleRpc fields.
func (er *ExampleRpc) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case examplerpc.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			er.ID = int(value.Int64)
		default:
			er.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ExampleRpc.
// This includes values selected through modifiers, order, etc.
func (er *ExampleRpc) Value(name string) (ent.Value, error) {
	return er.selectValues.Get(name)
}

// Update returns a builder for updating this ExampleRpc.
// Note that you need to call ExampleRpc.Unwrap() before calling this method if this ExampleRpc
// was returned from a transaction, and the transaction was committed or rolled back.
func (er *ExampleRpc) Update() *ExampleRpcUpdateOne {
	return NewExampleRpcClient(er.config).UpdateOne(er)
}

// Unwrap unwraps the ExampleRpc entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (er *ExampleRpc) Unwrap() *ExampleRpc {
	_tx, ok := er.config.driver.(*txDriver)
	if !ok {
		panic("ent: ExampleRpc is not a transactional entity")
	}
	er.config.driver = _tx.drv
	return er
}

// String implements the fmt.Stringer.
func (er *ExampleRpc) String() string {
	var builder strings.Builder
	builder.WriteString("ExampleRpc(")
	builder.WriteString(fmt.Sprintf("id=%v", er.ID))
	builder.WriteByte(')')
	return builder.String()
}

// ExampleRpcs is a parsable slice of ExampleRpc.
type ExampleRpcs []*ExampleRpc
