// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// ExampleRpc is the predicate function for examplerpc builders.
type ExampleRpc func(*sql.Selector)
