// Code generated by goctl. DO NOT EDIT.
// Source: example_rpc.proto

package examplerpcclient

import (
	"context"

	"github.com/Sanagiig/fox-admin-core/example_rpc/types/examplerpc"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BaseIDInt32Resp  = examplerpc.BaseIDInt32Resp
	BaseIDInt64Resp  = examplerpc.BaseIDInt64Resp
	BaseIDResp       = examplerpc.BaseIDResp
	BaseIDStringResp = examplerpc.BaseIDStringResp
	BaseIDUint32Resp = examplerpc.BaseIDUint32Resp
	BaseResp         = examplerpc.BaseResp
	BaseUUIDResp     = examplerpc.BaseUUIDResp
	Empty            = examplerpc.Empty
	IDInt32Req       = examplerpc.IDInt32Req
	IDInt64Req       = examplerpc.IDInt64Req
	IDReq            = examplerpc.IDReq
	IDStringReq      = examplerpc.IDStringReq
	IDUint32Req      = examplerpc.IDUint32Req
	IDsInt32Req      = examplerpc.IDsInt32Req
	IDsInt64Req      = examplerpc.IDsInt64Req
	IDsReq           = examplerpc.IDsReq
	IDsStringReq     = examplerpc.IDsStringReq
	IDsUint32Req     = examplerpc.IDsUint32Req
	PageInfoReq      = examplerpc.PageInfoReq
	UUIDReq          = examplerpc.UUIDReq
	UUIDsReq         = examplerpc.UUIDsReq

	ExampleRpc interface {
		InitDatabase(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*BaseResp, error)
	}

	defaultExampleRpc struct {
		cli zrpc.Client
	}
)

func NewExampleRpc(cli zrpc.Client) ExampleRpc {
	return &defaultExampleRpc{
		cli: cli,
	}
}

func (m *defaultExampleRpc) InitDatabase(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*BaseResp, error) {
	client := examplerpc.NewExampleRpcClient(m.cli.Conn())
	return client.InitDatabase(ctx, in, opts...)
}
